name: Build_Aspen_SchemaSpy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build schemaspy document and deploy gh-pages
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: aspen
        ports:
          - 3306:3306
    steps:
      - name: Get schema file
        run: wget https://raw.githubusercontent.com/mdnoble73/aspen-discovery/22.02.00/install/aspen.sql
      - name: Sleep 1s
        run: sleep 1
      - name: Make build dir
        run: mkdir build 
      - name: List docker containers
        run: docker ps
      - name: Setup DB
        run: docker exec -i db sh -c 'exec mysql -uroot -ppassword' < aspen.sql 
      - name: Execute schemaspy
        run: docker run -v "$PWD/build:/output" schemaspy/schemaspy:latest
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
